version: '3.4'

services:
  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  exchange.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

